frr version 10.5.1
frr defaults traditional
hostname leaf2
no ipv6 forwarding
!
vrf vrf01c9a2a0762a
 vni 104000
exit-vrf
!
interface eth1
!
interface eth2
!
router bgp 65012
 bgp router-id 10.255.1.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor eth1 interface remote-as external
 neighbor eth2 interface remote-as external
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  neighbor eth1 activate
  neighbor eth2 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65012 vrf vrf01c9a2a0762a
 bgp router-id 10.255.1.2
 !
 address-family l2vpn evpn
  route-target both 999:100
  advertise ipv4 unicast
 exit-address-family
!
line vty
!
