frr version 10.5.1
frr defaults traditional
hostname leaf2
no ipv6 forwarding
!
vrf vrf01c9a2a0762a
exit-vrf
!
interface eth1
 ip address 10.0.3.2/30
!
interface eth2
 ip address 10.0.4.1/30
!
router bgp 65012 vrf vrf01c9a2a0762a
 bgp router-id 10.255.1.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.3.1 remote-as 65021
 neighbor 10.0.4.2 remote-as 65002
 !
 address-family ipv4 unicast
 exit-address-family
!
line vty
!
