frr version 10.5.1
frr defaults traditional
hostname host1
no ipv6 forwarding
!
vrf vrf01c9a2a0762a
exit-vrf
!
interface eth1
 ip address 10.0.1.1/30
!
router bgp 65001 vrf vrf01c9a2a0762a
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.1.2 remote-as 65011
 !
 address-family ipv4 unicast
  redistribute static
 exit-address-family
!
line vty
!
